[package]
name = "rust-crash-course-exercises"
version = "0.1.0"
authors = ["Francisco Perez-Sorrosal <fperezsorrosal@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
